{% set name = "scmrepo" %}
{% set version = "0.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scmrepo-{{ version }}.tar.gz
  sha256: 1d8238812c00cb44a3acd2ce0e20b9d7fa330dc282a74dd52a9db4d12c4f339b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm >=6.3.1
  run:
    - asyncssh <3,>=2.7.1
    - dulwich >=0.20.34
    - fsspec >=2021.7.0
    - funcy >=1.14
    - gitpython >3
    - pathspec <0.10.0,>=0.9.0
    - pygit2 >=1.10.0
    - pygtrie >=2.3.2
    - python >=3.7

test:
  imports:
    - scmrepo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/iterative/scmrepo
  summary: SCM wrapper and fsspec filesystem for Git for use in DVC
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - skshetry
    - efiop
    - pmrowla
    - dtrifiro
    - shcheklein
