{% set name = "scmrepo" %}
{% set version = "0.0.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scmrepo-{{ version }}.tar.gz
  sha256: 44764b527d113583e26097e56e11f49428e2bd5145200c383c0e9a9c31a391cd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - asyncssh <2.9,>=2.7.1
    - dulwich >=0.20.23
    - fsspec >=2021.7.0
    - funcy >=1.14
    - gitpython >3
    - pathspec <0.10.0,>=0.9.0
    - pygit2 >=1.5.0
    - pygtrie >=2.3.2
    - python >=3.7

test:
  imports:
    - scmrepo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/iterative/scmrepo
  summary: SCM wrapper and fsspec filesystem for Git for use in DVC
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - skshetry
    - efiop
